### PR TITLE
Add a strict option to ignore html errors

### PR DESCRIPTION
**Pull request by janxious**
And clean up a bunch of whitespace, I guess?

### CODE REVIEW

**Comment by krewenki** [comment]
I'm lazy, my apologies.  When I viewed the diff, it looked like the whole file had changed.  I'll look through your individual commits to see if I can figure out what you did, and merge if it all looks good.

**Comment by janxious** [comment]
Hmm. I am guessing my emacs config replaced a bunch of tabs with spaces.

**Comment by janxious** [comment]
bump

**Comment by apmsooner** [comment]
I made the exact same changes as janxious to add strict to fields list. Can you commit this?

**Comment by markushausammann** [comment]
Seems this project is dead then?

**Pull request closed without merging**
